version: '3.8'

services:
  compare:
    # Nome da imagem que ser치 gerada e pode ser enviada ao Docker Hub
    image: damascenod/compare
    # Constr칩i a imagem a partir do Dockerfile no diret칩rio atual
    build: .
    # Mapeia a porta 8000 do container para a porta 8000 da sua m치quina
    ports:
      - "8000:8000"
    # Reinicia o container automaticamente em caso de falha
    restart: unless-stopped