name: Publicar Imagem Docker

on:
  # Gatilho de push para a branch main
  push:
    branches:
      - 'main'
  
  # NOVO: Gatilho para execução manual (workflow_dispatch)
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch para construir a imagem'
        required: true
        default: 'main'

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      # Checkout do código, usando a branch do input manual se aplicável
      - name: Checkout do repositório
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.branch || github.ref }}

      # NOVO PASSO: Ler a versão do arquivo VERSION
      - name: Ler a versão do arquivo
        id: get_version
        run: echo "VERSION=$(cat VERSION)" >> $GITHUB_OUTPUT

      - name: Login no Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # ATUALIZADO: Extração de metadados com a nova tag de versão
      - name: Extrair metadados da imagem Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: damascenod/compare
          tags: |
            # Adiciona a tag 'latest' para pushes na branch main
            type=raw,value=latest,enable={{is_default_branch}}
            # Adiciona a tag lida do arquivo VERSION
            type=raw,value=${{ steps.get_version.outputs.VERSION }},enable=true

      - name: Construir e enviar imagem Docker
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}