name: Publicar Imagem Docker

on:
  # O workflow agora roda apenas em push para 'main' ou manualmente.
  push:
    branches:
      - 'main'
  
  # Gatilho para execução manual continua disponível
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch para construir a imagem'
        required: true
        default: 'main'

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.branch || github.ref }}

      - name: Ler a versão do arquivo
        id: get_version
        run: echo "VERSION=$(cat VERSION)" >> $GITHUB_OUTPUT

      - name: Login no Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Extrair metadados da imagem Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: damascenod/compare
          tags: |
            type=raw,value=latest,enable={{is_default_branch}}
            type=raw,value=${{ steps.get_version.outputs.VERSION }},enable=true

      - name: Construir e enviar imagem Docker
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}